#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>
#include <storage/storage.h>
#include <dolphin/dolphin.h>

/* generated by fbt from .png files in images folder */
#include <f0blackjack_icons.h>

typedef struct {
    uint8_t x;
    uint8_t y;
} Point;

typedef struct ViewPort ViewPort;

bool backpressed = false;
bool menu = true;

void render_callback(Canvas* canvas, void* context) {
    UNUSED(context);
    canvas_draw_icon(canvas, 0, 0, &I_title);
}

void input_callback(InputEvent* event, void* context) {
    UNUSED(context);
    if(event->type == InputTypePress) {
        if(event->key == InputKeyUp) {
            FURI_LOG_I("INPUT", "Up Pressed");
        }
        if (event->key == InputKeyBack) {
            backpressed = true;
        }
    }
}

int32_t f0blackjack_app(void* p) {
    UNUSED(p);

    Gui* gui = furi_record_open("gui");

    ViewPort* viewport = view_port_alloc();
    view_port_draw_callback_set(viewport, render_callback, NULL);
    view_port_input_callback_set(viewport, input_callback, NULL);

    gui_add_view_port(gui, viewport, GuiLayerFullscreen);

    // Main loop: keep running until OK is pressed
    while (!backpressed) {
        furi_delay_ms(10);
    }

    // Cleanup before exit
    gui_remove_view_port(gui, viewport);
    view_port_free(viewport);
    furi_record_close("gui");

    return 0;
}
