#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>
#include <storage/storage.h>
#include <dolphin/dolphin.h>
#include <flipper_format/flipper_format.h>
/* generated by fbt from .png files in images folder */
#include <f0blackjack_icons.h>

typedef struct {
    bool backpressed;
    bool okpressed;
    bool menu;
} GameState;

void render_callback(Canvas* canvas, void* context) {
    UNUSED(context);
    canvas_draw_icon(canvas, 0, 0, &I_title);
}

void input_callback(InputEvent* event, void* context) {
    GameState* state = (GameState*)context;

    if(event->type == InputTypePress) {
        if(event->key == InputKeyUp) {
            FURI_LOG_I("INPUT", "Up Pressed");
        }
        if (event->key == InputKeyBack) {
            state->backpressed = true;
        }
        if (event->key == InputKeyOk) {
            state->okpressed = true;  // <-- Added missing semicolon
        }
    }
}

int32_t f0blackjack_app(void* p) {
    UNUSED(p);

    Gui* gui = furi_record_open("gui");

    ViewPort* viewport = view_port_alloc();

    // Initialize the game state
    GameState game_state = {false, false, true};

    view_port_draw_callback_set(viewport, render_callback, NULL);
    view_port_input_callback_set(viewport, input_callback, &game_state);  // Corrected pointer passing

    gui_add_view_port(gui, viewport, GuiLayerFullscreen);

    // Main loop: keep running until back is pressed while in menu
    while (true) {
        if (game_state.backpressed && game_state.menu) {  // Corrected variable access
            break;
        }
        furi_delay_ms(10);
    }

    // Cleanup before exit
    gui_remove_view_port(gui, viewport);
    view_port_free(viewport);
    furi_record_close("gui");

    return 0;
}
